Book/urls.py
from django.urls import path
from .views import (PeopleListView,
                    CreatePersonView,
                    DeletePersonView,
                    UpdatePersonView,
                    AddPhoneNumberView,
                    AddEmailView)

app_name = 'person'
urlpatterns = [
    path('', PeopleListView.as_view(), name='people_list'),
    path('add/', CreatePersonView.as_view(), name='create_person'),
    path('delete/<int:id>', DeletePersonView.as_view(), name='delete_person'),
    path('update/<int:id>', UpdatePersonView.as_view(), name='update_person'),
    path('add-number/<int:id>', AddPhoneNumberView.as_view(), name='add_number'),
    path('add-email/<int:id>', AddEmailView.as_view(), name='add_email')
]

PhoneBook/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('Book.urls', namespace='person'))
]

Book/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    class Meta:
        ordering = ('last_name', )

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def no_emails_or_numbers(self):
        if not self.email_set.all() and not self.phone_set.all():
            return True
        return False


class Phone(models.Model):
    phone = models.CharField(max_length=50)
    person = models.ForeignKey(Person,
                               on_delete=models.CASCADE, editable=False)


class Email(models.Model):
    email = models.EmailField()
    person = models.ForeignKey(Person,
                               on_delete=models.CASCADE, editable=False)

Book/forms.py
import re
from django.forms import ModelForm, ValidationError

from .models import Person, Phone, Email


class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name']
        labels = {
            'first_name': 'Imie',
            'last_name': 'Nazwisko',
        }


class PhoneForm(ModelForm):
    class Meta:
        model = Phone
        fields = ['phone']
        labels = {'phone': 'Numer telefonu'}

    def clean_phone(self):
        pattern = re.compile(r'^\d{3}-\d{3}-\d{3}$|^\d{2}-\d{3}-\d{2}-\d{2}$')
        phone = self.cleaned_data['phone']
        if not pattern.fullmatch(phone):
            raise ValidationError('Niewłaściwy numer telefonu')
        return phone


class EmailForm(ModelForm):
    class Meta:
        model = Email
        fields = ['email']
        labels = {'email': 'Adres email'}

    def clean_email(self):
        pattern = re.compile(r'^(?!\d).*[a-zA-Z0-9]*@(\w*.\w*)|(\w*.)|.(\w*)$')
        email = self.cleaned_data['email']
        if not pattern.fullmatch(email):
            raise ValidationError('Niewłaściwy adres e-mail')
        return email

Book/views.py
from django.views.generic import (ListView,
                                  CreateView,
                                  DeleteView,
                                  UpdateView)
from django.db.models import Q
from django.shortcuts import reverse, get_object_or_404
from .models import Person, Phone, Email
from .forms import PersonForm, PhoneForm, EmailForm


class PeopleListView(ListView):
    context_object_name = 'people'
    template_name = 'person/people_list.html'
    paginate_by = 5

    def get_queryset(self):
        """get_queryset method overridden for
        implementing basic search engine"""
        query = self.request.GET.get('query')
        category = self.request.GET.get('category')
        if category == 'first_name':
            people = Person.objects.filter(Q(first_name__icontains=query))
        elif category == 'last_name':
            people = Person.objects.filter(Q(last_name__icontains=query))
        elif category == 'phone':
            people = Person.objects.filter(Q(phone__phone__contains=query))
        elif category == 'email':
            people = Person.objects.filter(Q(email__email__contains=query))
        else:
            people = Person.objects.all()
        return people


class CreatePersonView(CreateView):
    form_class = PersonForm
    model = Person
    template_name = 'person/add_person.html'

    def get_success_url(self):
        return reverse('person:people_list')


class DeletePersonView(DeleteView):
    model = Person
    context_object_name = 'person'
    template_name = 'person/delete_person.html'

    def get_object(self, **kwargs):
        person_id = self.kwargs.get('id')
        return get_object_or_404(Person, id=person_id)

    def get_success_url(self):
        return reverse('person:people_list')


class UpdatePersonView(UpdateView):
    model = Person
    form_class = PersonForm
    template_name = 'person/update_person.html'

    def get_object(self, **kwargs):
        person_id = self.kwargs.get('id')
        return get_object_or_404(Person, id=person_id)

    def get_success_url(self):
        return reverse('person:people_list')


class AddPhoneNumberView(CreateView):
    model = Phone
    form_class = PhoneForm
    template_name = 'person/add_phone.html'

    def form_valid(self, form):
        phone = form.save(commit=False)
        phone.person_id = self.kwargs.get('id')
        return super(AddPhoneNumberView, self).form_valid(form)

    def get_success_url(self):
        return reverse('person:people_list')


class AddEmailView(CreateView):
    model = Email
    form_class = EmailForm
    template_name = 'person/add_email.html'

    def form_valid(self, form):
        email = form.save(commit=False)
        email.person_id = self.kwargs.get('id')
        return super(AddEmailView, self).form_valid(form)

    def get_success_url(self):
        return reverse('person:people_list')

Book/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Książka telefoniczna</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="navbar-brand">
            <h3>
                <a class="a-title" href="{% url 'person:people_list' %}">
                    Książka telefoniczna
                </a>
            </h3>
        </div>
        {% block additional_nav %}
        {% endblock %}
        <button class="navbar-toggler navbar-nav ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Book/templates/pagination.html
<div class="paginator">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <span class="current">
            Strona {{ page.number }} z {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Następna</a>
        {% endif %}
    </span>
</div>

Book/templates/person/add_email.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Podaj adres email.</p>
        {{ form }}
        <input type="submit" value="Dodaj adres e-mail">
        <a href="{% url 'person:people_list' %}">Anuluj</a>
    </form>
{% endblock %}

Book/templates/person/add_person.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Dodaj">
        <a href="{% url 'person:people_list' %}">Anuluj</a>
    </form>
{% endblock %}

Book/templates/person/add_phone.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Podaj nr telefonu w formacie xxx-xxx-xxx lub xx-xxx-xx-xx</p>
        {{ form.as_p }}
        <input type="submit" value="Dodaj nr telefonu">
        <a href="{% url 'person:people_list' %}">Anuluj</a>
    </form>
{% endblock %}

Book/templates/person/delete_person.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <label>Czy jestę pewien że chcesz usunąć użytkownika {{ person }}?</label>
        <input type="submit" value="tak">
        <a href="{% url 'person:people_list' %}">Nie</a>
    </form>
{% endblock %}

Book/templates/person/people_list.html
{% extends 'base.html' %}
{% block additional_nav %}
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="navbar-item navbar-nav ml-auto nav-buttons">
                <form method="get">
                    <label class="search-label" for="search-select-category">Wyszukaj po:</label>
                    <select id="search-select-category" name="category">
                        <option value="first_name">Imie</option>
                        <option value="last_name" selected>Nazwisko</option>
                        <option value="phone">Numer telefonu</option>
                        <option value="email">E-mail</option>
                    </select>
                    <input type="text" name="query" value="{{ request.GET.q }}">
                    <input class="btn btn-light" type="submit" value="Szukaj">
                </form>
            </li>
            <li class="navbar-item navbar-nav ml-auto nav-buttons">
                <a href="{% url 'person:create_person' %}">
                    <button class="btn btn-light">Dodaj osobę</button>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}
{% block content %}
    {% if people %}
    {% for person in people %}
        <div class="card">
            <div class="card-body">
                <h4>{{ person }}</h4>
                {% if not person.phone_set.all %}
                    <p class="person-contacts">Ta osoba nie posiada numerów telefonu.</p>
                {% else %}
                    <ul class="person-contacts">
                        {% for phone in person.phone_set.all %}
                            <li>{{ phone.phone }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if not person.email_set.all %}
                    <p class="person-contacts">Ta osoba nie posiada skrzynek e-mail</p>
                {% else %}
                    <ul class="person-contacts">
                        {% for email in person.email_set.all %}
                            <li>{{ email.email }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

            </div>
            <div class="person-buttons">
                <a class="card-link" href="{% url 'person:update_person' person.pk %}">Edytuj imię i nazwisko</a>
                <a class="card-link" href="{% url 'person:add_email' person.pk %}">Dodaj adres e-mail</a>
                <a class="card-link" href="{% url 'person:add_number' person.pk %}">Dodaj nr telefonu</a>
                {% if person.no_emails_or_numbers %}
                    <a class="card-link" href="{% url 'person:delete_person' person.pk %}">Usuń</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    {% else %}
        <p>Brak osób do wyświetlenia</p>
    {% endif %}
    {% include 'pagination.html' with page=page_obj %}
{% endblock %}

Book/templates/person/update_person.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Zatwierdź zmiany">
        <a href="{% url 'person:people_list' %}">Anuluj</a>
    </form>
{% endblock %}